// Generates two type-only declaration files into
// packages-tooling/testkit/testkit-vitest/src/, each a list of
// `import type {} from "<plugin>/testkit"` statements that pull plugin
// augmentations (.mock/.spy/.routing/etc.) onto plugin schemas:
//
//   extensions.d.ts
//     Published packages only. Referenced as the `types` condition of
//     testkit-vitest's main export (see grest.package.ts → typesOverride),
//     so npm consumers get augmentations for the packages they can install.
//     The packager derives testkit-vitest's peerDependencies from these
//     imports, so it must not name a private package.
//
//   extensions.unpublished-packages.d.ts
//     Only the private (unpublished) packages — a supplement, not a superset.
//     Exposed as the "./unpublished-packages" subpath. The monorepo's own
//     examples/tests list BOTH "@grest-ts/testkit-vitest" (the published set,
//     so they exercise the same types path real npm consumers get) and
//     "@grest-ts/testkit-vitest/unpublished-packages" (these extras), so a
//     newly-added private plugin's augmentations are present without
//     per-package wiring. GGParser ignores **/*.unpublished-packages.d.ts, so
//     its private imports never become peerDependencies.
//
// Runtime registration of the same extensions flows through
// GGExtensionDiscovery.load() at test boot; types and runtime are separate.
//
// Regenerated by `npm run check` (grest.1.check.ts) and `tsx grest.4.build.ts`.
// Gitignored via the global `**/*.d.ts` rule.

import {existsSync, readFileSync, readdirSync, writeFileSync} from "fs"
import {join, resolve} from "path"

const ROOT = resolve(import.meta.dirname, "..", "..")
const SRC_DIR = join(ROOT, "packages-tooling/testkit/testkit-vitest/src")
const PUBLISHED_OUTPUT = join(SRC_DIR, "extensions.d.ts")
const UNPUBLISHED_OUTPUT = join(SRC_DIR, "extensions.unpublished-packages.d.ts")
const WORKSPACE_ROOTS = ["packages", "packages-libs", "packages-tooling"]

interface TestkitPackage {
    name: string
    published: boolean
}

function readPackage(dir: string): TestkitPackage | null {
    const pkgPath = join(dir, "package.json")
    if (!existsSync(pkgPath)) return null
    try {
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
        if (!pkg.name) return null
        return {name: pkg.name, published: pkg.private !== true}
    } catch {
        return null
    }
}

function findTestkitPackages(): TestkitPackage[] {
    const found: TestkitPackage[] = []
    for (const wsRoot of WORKSPACE_ROOTS) {
        const wsDir = join(ROOT, wsRoot)
        if (!existsSync(wsDir)) continue
        for (const entry of readdirSync(wsDir, {withFileTypes: true})) {
            if (!entry.isDirectory() || entry.name === "node_modules") continue
            visit(join(wsDir, entry.name), found, 0)
        }
    }
    const byName = new Map(found.map(p => [p.name, p]))
    return [...byName.values()].sort((a, b) => a.name.localeCompare(b.name))
}

function visit(dir: string, found: TestkitPackage[], depth: number): void {
    if (existsSync(join(dir, "testkit/index-testkit.ts"))) {
        const pkg = readPackage(dir)
        if (pkg) found.push(pkg)
    }
    if (depth >= 1) return
    for (const sub of readdirSync(dir, {withFileTypes: true})) {
        if (!sub.isDirectory() || sub.name === "node_modules") continue
        visit(join(dir, sub.name), found, depth + 1)
    }
}

function writeReferences(outPath: string, names: string[]): void {
    const lines = [
        "// AUTO-GENERATED by scripts/packager/generate-testkit-extensions.ts — DO NOT EDIT.",
        "// Regenerated by `npm run check` and `tsx grest.4.build.ts`.",
        "",
    ]
    for (const name of names) {
        // @ts-ignore handles consumers that don't install this plugin.
        lines.push(`// @ts-ignore`)
        lines.push(`import type {} from "${name}/testkit";`)
    }
    lines.push("")
    writeFileSync(outPath, lines.join("\n"))
}

export function generateTestkitExtensions(): void {
    const packages = findTestkitPackages()
    const published = packages.filter(p => p.published).map(p => p.name)
    const unpublished = packages.filter(p => !p.published).map(p => p.name)
    writeReferences(PUBLISHED_OUTPUT, published)
    writeReferences(UNPUBLISHED_OUTPUT, unpublished)
    console.log(`[testkit-extensions] Wrote ${published.length} published → ${PUBLISHED_OUTPUT}`)
    console.log(`[testkit-extensions] Wrote ${unpublished.length} unpublished → ${UNPUBLISHED_OUTPUT}`)
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
    generateTestkitExtensions()
}
