// Generates packages-tooling/testkit/testkit-vitest/src/extensions.d.ts —
// a pure declaration file containing type-only `import type {} from
// "<plugin>/testkit"` statements, one per published monorepo package that
// ships a testkit extension.
//
// The file is referenced as the `types` condition of testkit-vitest's main
// export (see grest.package.ts → typesOverride), so any consumer who lists
// "@grest-ts/testkit-vitest" in tsconfig `types` gets plugin augmentations
// (.mock/.spy/.routing/etc.) typed on plugin schemas — no consumer-side
// codegen.
//
// Runtime registration of the same extensions still flows through
// GGExtensionDiscovery.load() at test boot; types and runtime are
// separate concerns.
//
// Regenerated by `npm run check` (grest.1.check.ts) and `tsx grest.4.build.ts`.
// Gitignored via the global `**/*.d.ts` rule.

import {existsSync, readFileSync, readdirSync, writeFileSync} from "fs"
import {join, resolve} from "path"

const ROOT = resolve(import.meta.dirname, "..", "..")
const OUTPUT = join(ROOT, "packages-tooling/testkit/testkit-vitest/src/extensions.d.ts")
const WORKSPACE_ROOTS = ["packages", "packages-libs", "packages-tooling"]

// Skip private (unpublished) packages: testkit-vitest derives its peerDeps from
// the imports in this generated file, so referencing a private package would add
// a peerDep on something outside the npm publish set and fail publish validation.
// Consumers can't install private packages anyway.
function readPublishedPackageName(dir: string): string | null {
    const pkgPath = join(dir, "package.json")
    if (!existsSync(pkgPath)) return null
    try {
        const pkg = JSON.parse(readFileSync(pkgPath, "utf-8"))
        if (pkg.private) return null
        return pkg.name ?? null
    } catch {
        return null
    }
}

function findTestkitPackages(): string[] {
    const found: string[] = []
    for (const wsRoot of WORKSPACE_ROOTS) {
        const wsDir = join(ROOT, wsRoot)
        if (!existsSync(wsDir)) continue
        for (const entry of readdirSync(wsDir, {withFileTypes: true})) {
            if (!entry.isDirectory() || entry.name === "node_modules") continue
            visit(join(wsDir, entry.name), found, 0)
        }
    }
    return [...new Set(found)].sort()
}

function visit(dir: string, found: string[], depth: number): void {
    if (existsSync(join(dir, "testkit/index-testkit.ts"))) {
        const name = readPublishedPackageName(dir)
        if (name) found.push(name)
    }
    if (depth >= 1) return
    for (const sub of readdirSync(dir, {withFileTypes: true})) {
        if (!sub.isDirectory() || sub.name === "node_modules") continue
        visit(join(dir, sub.name), found, depth + 1)
    }
}

export function generateTestkitExtensions(): void {
    const packages = findTestkitPackages()
    const lines = [
        "// AUTO-GENERATED by scripts/packager/generate-testkit-extensions.ts — DO NOT EDIT.",
        "// Regenerated by `npm run check` and `tsx grest.4.build.ts`.",
        "",
    ]
    for (const pkg of packages) {
        // @ts-ignore handles consumers that don't install this plugin.
        lines.push(`// @ts-ignore`)
        lines.push(`import type {} from "${pkg}/testkit";`)
    }
    lines.push("")
    writeFileSync(OUTPUT, lines.join("\n"))
    console.log(`[testkit-extensions] Wrote ${packages.length} type-only references → ${OUTPUT}`)
}

if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
    generateTestkitExtensions()
}
