services:
  verdaccio:
    image: verdaccio/verdaccio:6
    container_name: gg-verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./.verdaccio/storage:/verdaccio/storage
      - ./.verdaccio/config.yaml:/verdaccio/conf/config.yaml
    restart: unless-stopped
