import {GGTest} from "@grest-ts/testkit";
import {MainRuntime} from "../src/main";

describe("CORS auto-discovery", () => {

    GGTest.startInline(MainRuntime);

    test("useHeader codec correctly exposes inputKeys for auto-discovery", async () => {
        const {GG_INTL_LOCALE} = await import("@grest-ts/intl");
        const codec = GG_INTL_LOCALE.getCodec("http");
        expect(codec).toBeDefined();
        expect(codec!.inputKeys).toEqual(["accept-language"]);
    });

    test("middleware declares both headers and responseHeaders", async () => {
        const {ClientInfoEffect, FeatureFlagsEffect} = await import("../src/api/MiddlewareTestApi");
        expect(ClientInfoEffect.headers).toEqual(['x-client-version', 'x-client-platform']);
        expect(ClientInfoEffect.responseHeaders).toEqual([]);
        expect(FeatureFlagsEffect.headers).toEqual(['x-feature-flags']);
        expect(FeatureFlagsEffect.responseHeaders).toEqual([]);
    });

    test("middleware generated by useHeader includes codec inputKeys as headers", async () => {
        const {GGRpc, httpSchema} = await import("@grest-ts/http");
        const {GGContractClass, IsString} = await import("@grest-ts/schema");
        const {GGContextKey} = await import("@grest-ts/context");
        const {IsObject} = await import("@grest-ts/schema");

        const HeaderSchema = IsObject({"x-test-header": IsString.orUndefined});
        const ContextSchema = IsObject({value: IsString.orUndefined});

        const MY_CTX = new GGContextKey("test-ctx", ContextSchema);
        MY_CTX.addCodec("http", HeaderSchema.codecTo(ContextSchema, {
            encode: (h) => ({value: h["x-test-header"]}),
            decode: (c) => ({"x-test-header": c.value})
        }));

        const TestContract = new GGContractClass("CorsTestContract", {
            get: {success: IsString, errors: []}
        });

        const schema = httpSchema(TestContract)
            .pathPrefix("test")
            .useHeader(MY_CTX)
            .routes({get: GGRpc.GET("get")});

        const mw = schema.apiMiddlewares[0];
        expect(mw.headers).toEqual(["x-test-header"]);
        expect(mw.responseHeaders).toEqual([]);
    });

    test("codec declares responseHeaders for expose-headers auto-discovery", async () => {
        const {GGRpc} = await import("@grest-ts/http");
        const rpcCodec = GGRpc.GET("test");
        expect(rpcCodec.responseHeaders).toEqual([]);

        const {GGFileDownload} = await import("@grest-ts/http-file");
        const downloadCodec = GGFileDownload.GET("test");
        expect(downloadCodec.responseHeaders).toEqual(['Content-Disposition']);
    });
});
