import {GGTest} from "@grest-ts/testkit";
import {MainRuntime} from "../src/main";
import {GG_INTL_LOCALE} from "@grest-ts/intl";
import {GGRpc, httpSchema} from "@grest-ts/http";
import {GGContractClass, IsObject, IsString} from "@grest-ts/schema";
import {GGContextKey} from "@grest-ts/context";
import {GGFileDownload} from "@grest-ts/http-file";
import {ClientInfoEffect, FeatureFlagsEffect} from "../src/api/MiddlewareTestApi";

describe("CORS auto-discovery", () => {

    GGTest.startInline(MainRuntime);

    test("useHeader codec correctly exposes inputKeys for auto-discovery", () => {
        const codec = GG_INTL_LOCALE.getCodec("http");
        expect(codec).toBeDefined();
        expect(codec!.inputKeys).toEqual(["accept-language"]);
    });

    test("middleware declares both headers and responseHeaders", () => {
        expect(ClientInfoEffect.headers).toEqual(['x-client-version', 'x-client-platform']);
        expect(ClientInfoEffect.responseHeaders).toEqual([]);
        expect(FeatureFlagsEffect.headers).toEqual(['x-feature-flags']);
        expect(FeatureFlagsEffect.responseHeaders).toEqual([]);
    });

    test("middleware generated by useHeader includes codec inputKeys as headers", () => {
        const HeaderSchema = IsObject({"x-test-header": IsString.orUndefined});
        const ContextSchema = IsObject({value: IsString.orUndefined});

        const MY_CTX = new GGContextKey("test-ctx", ContextSchema);
        MY_CTX.addCodec("http", HeaderSchema.codecTo(ContextSchema, {
            encode: (h) => ({value: h["x-test-header"]}),
            decode: (c) => ({"x-test-header": c.value})
        }));

        const TestContract = new GGContractClass("CorsTestContract", {
            get: {success: IsString, errors: []}
        });

        const schema = httpSchema(TestContract)
            .pathPrefix("test")
            .useHeader(MY_CTX)
            .routes({get: GGRpc.GET("get")});

        const mw = schema.apiMiddlewares[0];
        expect(mw.headers).toEqual(["x-test-header"]);
        expect(mw.responseHeaders).toEqual([]);
    });

    test("codec declares responseHeaders for expose-headers auto-discovery", () => {
        const rpcCodec = GGRpc.GET("test");
        expect(rpcCodec.responseHeaders).toEqual([]);

        const downloadCodec = GGFileDownload.GET("test");
        expect(downloadCodec.responseHeaders).toEqual(['Content-Disposition']);
    });
});
