import {definePackage} from "#scripts/packager/definePackage";

definePackage({
    name: "@grest-ts/testkit-vitest",
    description: "Component testing library integration for vitest",
    keywords: ["testing", "vitest", "testkit"],
    targets: {node: true},
    hasTests: true,
    publishToNpm: true,
    customExports: {
        "./globalSetup": "./src/globalSetup.ts"
    },
    // Generated by scripts/packager/generate-testkit-extensions.ts. Points
    // the main `types` condition at a pure .d.ts so source-mode consumers
    // (whose package.json `exports.types` would otherwise resolve to .ts
    // and fail the .ts→.d.ts stripping done by tsconfig `types`) work.
    typesOverride: "./src/extensions.d.ts"
})
