import { join } from "path"
import { existsSync, readFileSync } from "fs"
import type { GGPackageInfo } from "./GGParser"
import { PackagerFile } from "./PackagerFile"

/**
 * Generates a per-package "duplicate-load detector" that throws if the same
 * package is loaded twice in one process (e.g. once from a bundle, once from
 * node_modules; or once from each of two node_modules trees).
 *
 * Why a separate file (and not inline in the entry):
 *   ESM hoists all `import` / `export *` statements to module-link time, so
 *   any side-effect of imported modules (e.g. `new GGIssueInvalid(...)` as a
 *   static class field that auto-registers in GGIssueRegistry) runs *before*
 *   any top-level statement of the entry file. To beat those side effects,
 *   the dedup check has to be its own leaf module imported *first* by the
 *   entry — leaf modules evaluate before their parent, and import order
 *   within a module is preserved during evaluation.
 *
 * The generator owns the leaf file completely and injects a single
 * `import "./_dedupCheck";` line at the top of each entry file.
 */
export class GGDedupCheckBuilder {

    private static readonly DEDUP_FILE_BASENAME = "_dedupCheck.ts"
    private static readonly DEDUP_IMPORT_LINE = `import "./_dedupCheck";`

    constructor(
        private readonly packages: GGPackageInfo[],
        private readonly version: string,
    ) {}

    build(): PackagerFile[] {
        const files: PackagerFile[] = []
        for (const pkg of this.packages) {
            files.push(...this.buildForPackage(pkg))
        }
        return files
    }

    buildForPackage(pkg: GGPackageInfo): PackagerFile[] {
        if (pkg.config.noSourceCode) return []

        const files: PackagerFile[] = []
        const srcDir = join(pkg.path, "src")

        // Generate the leaf file the entries import.
        files.push(PackagerFile.copy(
            join(srcDir, GGDedupCheckBuilder.DEDUP_FILE_BASENAME),
            this.renderDedupFile(pkg.name),
        ))

        // Inject the import line at the top of every entry file the package
        // exposes through its exports map.
        for (const entry of this.entryFilesFor(pkg)) {
            const updated = this.injectImport(entry)
            if (updated !== null) files.push(updated)
        }

        return files
    }

    private entryFilesFor(pkg: GGPackageInfo): string[] {
        const srcDir = join(pkg.path, "src")
        const candidates: string[] = []

        if (pkg.entryMode === "library") {
            candidates.push(join(srcDir, "index.ts"))
        } else {
            if (pkg.config.targets?.node) candidates.push(join(srcDir, "index-node.ts"))
            if (pkg.config.targets?.browser) candidates.push(join(srcDir, "index-browser.ts"))
        }

        return candidates.filter(p => existsSync(p))
    }

    private injectImport(entryPath: string): PackagerFile | null {
        const original = readFileSync(entryPath, "utf-8")
        if (original.includes(GGDedupCheckBuilder.DEDUP_IMPORT_LINE)) {
            // Already present somewhere — leave the file alone.
            return null
        }
        const updated = GGDedupCheckBuilder.DEDUP_IMPORT_LINE + "\n" + original
        return PackagerFile.copy(entryPath, updated)
    }

    private renderDedupFile(packageName: string): string {
        return `// =============================================================================
// THIS FILE IS GENERATED - DO NOT EDIT
//
// Detects duplicate loads of ${packageName}. Two copies of a grest-ts
// framework package in the same process break async context, validation
// registries, and service discovery. Throw with both paths so the packaging
// mistake is immediately diagnosable.
//
// Generated by scripts/packager — re-run \`npm run generate\` to refresh.
// =============================================================================

const __KEY = Symbol.for("grest-ts:dedup:${packageName}");
const __slot = globalThis as Record<symbol, unknown>;
const __existing = __slot[__KEY] as { path: string; version: string } | undefined;
const __here = { path: import.meta.url, version: "${this.version}" };
// Same path + same version means the same physical package is being
// re-evaluated by a different ESM runner (e.g. vitest projects share one
// process but each project has its own module cache). That isn't a true
// duplicate package — only differing paths or versions are.
if (__existing && (__existing.path !== __here.path || __existing.version !== __here.version)) {
    throw new Error(
        "[${packageName}] Duplicate package load detected.\\n" +
        "  Already loaded: " + __existing.path + " (v" + __existing.version + ")\\n" +
        "  Now loading:    " + __here.path + " (v" + __here.version + ")\\n" +
        "Two copies of grest-ts framework packages in one process break\\n" +
        "async context, validation, and service discovery. Fix the packaging."
    );
}
__slot[__KEY] = __here;
`
    }
}
