import {GGSchema} from "../../GGSchema";
import {AOT_Is} from "./impl/AOT_Is";
import {AOT_Validate} from "./impl/AOT_Validate";
import {AOT_Clean} from "./impl/AOT_Clean";
import {AOT_Stringify} from "./impl/AOT_Stringify";
import * as fs from "fs";

/**
 * Which functions to generate for each schema
 */
export interface TypeCompilerOptions {
    is?: boolean;
    validate?: boolean;
    clean?: boolean;
    stringify?: boolean;
}

const DEFAULT_OPTIONS: TypeCompilerOptions = {
    is: true,
    validate: true,
    clean: true,
    stringify: true
};

interface SchemaEntry {
    name: string;
    schema: GGSchema<any>;
    options: TypeCompilerOptions;
}

/**
 * TypeCompiler - Exports GGSchema validators as readable JavaScript code.
 *
 * This is for analysis and comparison with other AOT libraries
 * like Typia and ts-runtime-checks.
 *
 * @example
 * ```typescript
 * import { TypeCompiler } from '@grest-ts/schema';
 * import { IsObject, IsString, IsNumber } from '@grest-ts/schema';
 *
 * const User = IsObject({ name: IsString, age: IsNumber });
 * const Post = IsObject({ title: IsString, views: IsNumber });
 *
 * new TypeCompiler()
 *     .add('User', User)
 *     .add('Post', Post, { is: true, validate: false })
 *     .write('./generated-validators.js');
 * ```
 */
export class TypeCompiler {
    private entries: SchemaEntry[] = [];

    /**
     * Add a schema to be compiled
     * @param name - Name for the generated functions (e.g., 'User' -> User_is, User_validate, etc.)
     * @param schema - The GGSchema to compile
     * @param options - Which functions to generate (default: all)
     */
    add(name: string, schema: GGSchema<any>, options?: TypeCompilerOptions): this {
        this.entries.push({
            name,
            schema,
            options: {...DEFAULT_OPTIONS, ...options}
        });
        return this;
    }

    /**
     * Generate the code as a string
     */
    compile(): string {
        const lines: string[] = [
            '// ============================================================',
            '// Generated by @grest-ts/schema TypeCompiler',
            '// For analysis - compare with Typia, ts-runtime-checks, etc.',
            '// ============================================================',
            ''
        ];

        for (const entry of this.entries) {
            lines.push('// ──────────────────────────────────────────────────────────');
            lines.push(`// ${entry.name}`);
            lines.push('// ──────────────────────────────────────────────────────────');
            lines.push('');

            if (entry.options.is) {
                const code = new AOT_Is().compileToCode(entry.schema);
                lines.push(`// ${entry.name}.is(v) - Type guard`);
                lines.push(`const ${entry.name}_is = ${code};`);
                lines.push('');
            }

            if (entry.options.validate) {
                const code = new AOT_Validate().compileToCode(entry.schema);
                lines.push(`// ${entry.name}.validate(v, issues, path) - Validation with error collection`);
                lines.push(`const ${entry.name}_validate = ${code};`);
                lines.push('');
            }

            if (entry.options.clean) {
                const code = new AOT_Clean().compileToCode(entry.schema);
                lines.push(`// ${entry.name}.clean(v) - Strip extra properties`);
                lines.push(`const ${entry.name}_clean = ${code};`);
                lines.push('');
            }

            if (entry.options.stringify) {
                const code = new AOT_Stringify().compileToCode(entry.schema);
                lines.push(`// ${entry.name}.stringify(v) - Fast JSON serialization`);
                lines.push(`const ${entry.name}_stringify = ${code};`);
                lines.push('');
            }
        }

        return lines.join('\n');
    }

    /**
     * Write compiled code to a file
     */
    write(filePath: string): void {
        const code = this.compile();
        fs.writeFileSync(filePath, code, 'utf-8');
    }

    /**
     * Print compiled code to console
     */
    print(): void {
        console.log(this.compile());
    }
}
