name: Publish to NPM

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 25
        uses: actions/setup-node@v4
        with:
          node-version: 25

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx tsx grest.4.build.ts

      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npx tsx grest.5.npm.publish.ts --ci
